rmdir /s /q AgentVI\AgentVI\bin
rmdir /s /q AgentVI\AgentVI\obj
rmdir /s /q AgentVI\AgentVI.Android\bin
rmdir /s /q AgentVI\AgentVI.Android\obj
rmdir /s /q AgentVI\AgentVI.iOS\bin
rmdir /s /q AgentVI\AgentVI.iOS\obj
rmdir /s /q DummyProxy\bin
rmdir /s /q DummyProxy\obj
rmdir /s /q DummyProxyTest\bin
rmdir /s /q DummyProxyTest\obj
rmdir /s /q InnoviApiProxy\bin
rmdir /s /q InnoviApiProxy\obj
rmdir /s /q NadavTest\bin
rmdir /s /q NadavTest\obj